### ISSUE TITLE
Generate custom training extension

### ISSUE THREAD

**Issue by ibiliaiev** [amotruk/intro-to-hybris#5]
As a **Developer**
I need to have custom training extension,
So that I could add custom changes to this extension

**AC**:
Next extensions should be created:
training
package should be com.epam.training

**Technical tips**:
extgen util
yempty template
https://wiki.hybris.com/display/release5/Creating+a+New+Extension

**Comment by amotruk** [comment]
DONE in https://github.com/amotruk/intro-to-hybris/commit/423907678f2faf873c720c59595bb5bed5bf6019
